### ISSUE TITLE
选择视频进行分片上传时报错

### ISSUE THREAD

**Issue by kira2015** [WangYng/better_aliyun_oss#1]
<img width="764" alt="image" src="https://user-images.githubusercontent.com/14231117/179362444-da62e73b-18c1-40ce-90fd-7adfccd56da8.png">
jpg文件进行分片，没有问题，但选择mp4等视频文件分片，则DioError [DioErrorType.other]: SocketException: Connection reset by peer (OS Error: Connection reset by peer, errno = 54),

**Comment by kira2015** [comment]
flutter: 数据分片失败 BetterAliyunOssClientException{message: 上传失败}

**Comment by WangYng** [comment]
修复了。直接看Example里面如何分片上传的。
